### ISSUE TITLE
Dealing with WAV files of unknown length

### ISSUE THREAD

**Issue by gcohara** [Fluhzar/WAV#16]
It's sometimes desirable to upload a WAV to an OBS bucket.
However, the audio data is received via `Stream`, and there is no way to know the size of the file before upload begins (storing the entire file in memory would be undesirable, since they may be large).
The upload is carried out by first writing a header created by `Header::new`, and using `write` with the relevant writer and a `BitDepth` variant with an empty vector.
The audio data is then sent to the writer.
In this case it would be useful to have the header's size field set to `0xFFFFFFFF`.

Is there a way this could be handled? Perhaps by having `write` accept the `BitDepth::Empty` variant and write `0xFFFFFFFF` in the header?
I'd be happy to submit a PR.

**Comment by Fluhzar** [comment]
This project is largely a hobby project, written while I was still learning the language, so I hadn't planned on implementing streaming. But it has been brought up a few times now as a desired feature, so I decided a little while ago to just rewrite the project (now that I have a better grasp on the language) and have streaming part of the design from the start. I decided to use [`nom`](https://crates.io/crates/nom) as the base parser. `nom` comes with streaming capabilities, so it's a matter of building on top of that to get streaming for `wav` itself, and then deciding how to mimic the parsing API for writing.

If you could shed some light on your use case (or maybe just a link to info on an OBS bucket, I've never heard of that) it would be greatly appreciated!

If you'd like a feature like this to be brought in earlier than what I can probably do in the rewrite, then I would be happy to review a PR and release it as a 1.x release!

**Comment by Fluhzar** [comment]
See #17
