### ISSUE TITLE
Support streaming I/O

### ISSUE THREAD

**Issue by Ralith** [Fluhzar/WAV#5]
When processing large wav files, it may be undesirable to hold their contents in memory all at once. A mechanism to allow tracks to be read in or written out in chunks could make applications more efficient, or even be the difference between a task being feasible or not.

**Comment by Fluhzar** [comment]
Apologies in responding to this and the other issue you submitted, I'm in the middle of my final year of college so I'm pretty busy. As such I likely won't be able to get around to the issues for a while. If you or anyone else implements the changes with a pull request I'll be happy to take a little bit of time to merge the changes and upload the changes to crates.io

**Comment by Fluhzar** [comment]
@Ralith do you have any particular variation of streaming in mind that you'd like to see implemented? I don't have a lot of experience in this area, especially for rust, but I'm happy to take a look at possible implementations methods. With a quick search I see the [futures][0] crates has a [`Stream`][1] trait, is this something like what you're looking for?

[0]: https://crates.io/crates/futures
[1]: https://docs.rs/futures/0.3.8/futures/stream/trait.Stream.html

**Comment by Ralith** [comment]
That's probably not appropriate here. A simple approach could be something like:

```rust
pub struct Writer<W, T> { ... }
impl<W: io::Write, T: SampleType> Writer<W, T> {
    pub fn new(writer: W, header: Header) -> io::Result<Self>;
    pub fn write(&mut self, samples: &[T]) -> io::Result<()>;
}
```

This isn't really a pressing issue for me so I'm unlikely to pursue it personally.

**Comment by Fluhzar** [comment]
Looking into this with the `riff` crate dependency, it doesn't look like this is possible to implement. The `riff` crate reads and writes data from I/O in whole RIFF chunks, so to write partial data is not feasible. I could write my own code to write out RIFF data without the dependency, but that would add more development and maintenance work to my plate that I don't need. I'm going to close this until a more feasible solution arrives.
